// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package psqlrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int32            `db:"id" json:"id"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	OrderName  *string          `db:"order_name" json:"order_name"`
	CustomerID *int32           `db:"customer_id" json:"customer_id"`
}

type OrderItem struct {
	ID           int32          `db:"id" json:"id"`
	OrderID      *int32         `db:"order_id" json:"order_id"`
	PricePerUnit pgtype.Numeric `db:"price_per_unit" json:"price_per_unit"`
	Quantity     *int32         `db:"quantity" json:"quantity"`
	Product      *string        `db:"product" json:"product"`
}
