// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order_items.sql

package psqlrepo

import (
	"context"
)

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, price_per_unit, quantity, product FROM order_items
WHERE 1=1
`

func (q *Queries) GetOrderItems(ctx context.Context) ([]*OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PricePerUnit,
			&i.Quantity,
			&i.Product,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
