// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: orders.sql

package psqlrepo

import (
	"context"
)

const getOrders = `-- name: GetOrders :many
SELECT id, created_at, order_name, customer_id FROM orders
WHERE 1=1
`

func (q *Queries) GetOrders(ctx context.Context) ([]*Order, error) {
	rows, err := q.db.Query(ctx, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OrderName,
			&i.CustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
