// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package psqlrepo

import (
	"context"
)

type Querier interface {
	GetOrderItems(ctx context.Context) ([]*OrderItem, error)
	GetOrders(ctx context.Context) ([]*Order, error)
}

var _ Querier = (*Queries)(nil)
